### ISSUE TITLE
Illustrator port to WOL

### ISSUE THREAD

**Issue by MiMillieuh** [Windows-On-Linux/Repo#1]
Hello, 

Since I found your project really cool, I've ported Illustrator to it.

It should work like the Photoshop one since the install process is similar but it ships a custom wine so maybe it might break some things... I don't know but as I can see there aren't any sandboxes in your software so it shouldn't be an issue.

here is the branch with the build.sh.

https://github.com/MiMillieuh/Illustrator-CC-2021-Linux/tree/wolversion

Best of luck and keep going !

**Comment by andreock** [comment]
Thanks for work, I will add now

**Comment by andreock** [comment]
https://github.com/Windows-On-Linux/Repo/commit/1db43b0b33aa06cd03100c993d0f426fe1856944
